[versions]
kotlin = "2.3.20"

kotlinx-coroutines = "1.10.2"

ktor = "3.4.2"

bignum = "0.3.10"
semVer = "2.1.0"

kop = "0.0.7"
logback = "1.5.32"

dokka = "2.2.0"
kover = "0.9.8"
vanniktech-mavenPublish = "0.36.0"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

ktor-network = { group = "io.ktor", name = "ktor-network", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }

bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "bignum" }
semVer = { group = "net.swiftzer.semver", name = "semver", version.ref = "semVer" }

kop = { group = "io.github.domgew", name = "kop", version.ref = "kop" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-mavenPublish" }
