name: Test
on:
  push:
    branches:
      - "development"
    paths:
      - "kedis/**"
      - "gradle.properties"
      - "gradle/wrapper/**"
      - "gradle/libs.versions.toml"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "kedis/**"
      - "gradle.properties"
      - "gradle/wrapper/**"
      - "gradle/libs.versions.toml"
      - ".github/workflows/test.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis6:
        image: redis:6-alpine
        ports:
          - 6380:6379
      redis7:
        image: redis:7-alpine
        ports:
          - 6381:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test with Redis 6 on ${{ matrix.os }}
        run: |
          export IS_CI=yes
          export REDIS_PORT=6380
          ./gradlew cleanTest
          ./gradlew clean
          ./gradlew kedis:smartTest
      - name: Test reports for Redis 6 on ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-${{ github.sha }}-${{ matrix.os }}-redis-6
          path: |
            kedis/build/test-results/
            kedis/build/reports/tests/
          overwrite: true
      - name: Test with Redis 7 on ${{ matrix.os }}
        run: |
          export IS_CI=yes
          export REDIS_PORT=6381
          ./gradlew cleanTest
          ./gradlew clean
          ./gradlew kedis:smartTest
      - name: Test reports for Redis 7 on ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-${{ github.sha }}-${{ matrix.os }}-redis-7
          path: |
            kedis/build/test-results/
            kedis/build/reports/tests/
          overwrite: true
